server :
  port :  8769
  tomcat:
    uri-encoding: UTF-8

#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/tianglhtg?characterEncoding=UTF-8
#    username: ini
#    password: ini
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    master:
      jdbc-url: jdbc:mysql://10.1.0.213:3306/lhtg-app?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: rw_lhtg
      password: rw_lhtg001!!
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    slave:
      jdbc-url: jdbc:mysql://10.1.0.213:3307/lhtg-app?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      username: r_lhtg
      password: r_lhtg007!!
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:
    count: countSql

mybatis:
  mapper-locations: classpath*:/resources/mapper/*Mapper.xml
  type-aliases-package: com.tglh.simpleqigscanproject.mapper
